TriangleModels: TriangleModel.o TriangleModelTest.o
	g++ -o TriangleModels TriangleModel.o TriangleModelTest.o

TriangleModel.o: TriangleModel.cpp
	g++ -c TriangleModel.cpp

TriangleModelTest.o: TriangleModelTest.cpp
	g++ -c TriangleModelTest.cpp

clean:
	rm TriangleModels *.o


